### ISSUE TITLE
5.0.15 issue with go-reuseport

### ISSUE THREAD

**Issue by zippy** [libp2p/go-libp2p#295]
Hi folks, just updated my code to use 5.0.15 and in my build cycle I now see this:

```
../../../gx/ipfs/QmaBTcaZbAgei1Z2ksUipLJ2AeEZtqDnyGYAkL7NFJ8pg3/go-reuseport/impl_unix.go:99:16: cannot use sockaddrnet.NetAddrToSockaddr(dialer.LocalAddr) (type "golang.org/x/sys/unix".Sockaddr) as type "gx/ipfs/QmPXvegq26x982cQjSfbTvSzZXn7GiaMwhhVPHkeTEhrPT/sys/unix".Sockaddr in assignment:
	"golang.org/x/sys/unix".Sockaddr does not implement "gx/ipfs/QmPXvegq26x982cQjSfbTvSzZXn7GiaMwhhVPHkeTEhrPT/sys/unix".Sockaddr (missing "gx/ipfs/QmPXvegq26x982cQjSfbTvSzZXn7GiaMwhhVPHkeTEhrPT/sys/unix".sockaddr method)
```
Any idea why this might be happening?

To replicate:
```
$ go get -d -v github.com/Holochain/holochain-proto
$ cd $GOPATH/src/github.com/Holochain/holochain-proto
$ make hcdev
$ gx update go-libp2p QmXGfPjhnro8tgANHDUg4gGgLGYnAz1zcDPAgNeUkzbsN1
$ make hcdev
```

**Comment by vyzo** [comment]
I have seen this before -- I resolved by purging the gx cache.

**Comment by zippy** [comment]
you mean just delete `$GOPATH/src/gx`?  I tried that and it still happens.

However I did notice this, during the install I see this:

```
...
[done] [install] sys                           QmPXvegq26x982cQjSfbTvSzZXn7GiaMwhhVPHkeTEhrPT 257ms
[work] [install] go-sockaddr                   QmWBEjwiGM7mzpa2zkaen5PhxwRS4LrVRWAagBaPJio8eY
rewrite error:  /home/eric/go/src/gx/ipfs/QmWBEjwiGM7mzpa2zkaen5PhxwRS4LrVRWAagBaPJio8eY/go-sockaddr/net/net_bsd.go:26:15: expected type, found '=' (and 4 more errors)
rewrite error:  /home/eric/go/src/gx/ipfs/QmWBEjwiGM7mzpa2zkaen5PhxwRS4LrVRWAagBaPJio8eY/go-sockaddr/net/net_linux.go:24:15: expected type, found '=' (and 4 more errors)
[done] [install] go-sockaddr                   QmWBEjwiGM7mzpa2zkaen5PhxwRS4LrVRWAagBaPJio8eY 32msdr/net/net_windows.go:24:15: expected type, found '=' (and 4 more errors)
[done] [install] go-net-resolve-addr           Qma73Sqt13DzHzveZ667BBfraM7MuMrPepUXjmv812JhRS 25ms
...
```

**Comment by vyzo** [comment]
Uhm, what's your version of Go and gx? This look like issues with type aliases.

**Comment by zippy** [comment]
weird thing  I just did an update of gx:
```
$ gx --version
gx version 0.12.1
$ go version
go version go1.9.2 linux/amd64
```
and now the error happens during the gx update:

```
$ rm -rf ../../../gx/
$ gx update QmXGfPjhnro8tgANHDUg4gGgLGYnAz1zcDPAgNeUkzbsN1
rewrite error:  /home/eric/go/src/gx/ipfs/QmWBEjwiGM7mzpa2zkaen5PhxwRS4LrVRWAagBaPJio8eY/go-sockaddr/net/net_bsd.go:26:15: expected type, found '=' (and 4 more errors)
rewrite error:  /home/eric/go/src/gx/ipfs/QmWBEjwiGM7mzpa2zkaen5PhxwRS4LrVRWAagBaPJio8eY/go-sockaddr/net/net_linux.go:24:15: expected type, found '=' (and 4 more errors)
rewrite error:  /home/eric/go/src/gx/ipfs/QmWBEjwiGM7mzpa2zkaen5PhxwRS4LrVRWAagBaPJio8eY/go-sockaddr/net/net_windows.go:24:15: expected type, found '=' (and 4 more errors)
ERROR: unknown package:  go-libp2p
```

**Comment by vyzo** [comment]
these are certainly type aliases, but go1.9.x should understand them just fine.
@Stebalien any ideas here?

**Comment by Stebalien** [comment]
You may need to rebuild gx with go 1.9. That's the only explanation I can think of (unless it's some weird path issue).

**Comment by zippy** [comment]
I think that last one did it.  Thanks.
