### ISSUE TITLE
Be smarter when using MDNS

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#376]
We should:

1. Iterate over all the interfaces we're listening on that support multicast.
2. Figure out what IP addresses we have assigned on those interfaces.
3. Look up the IP in our host's listen addresses.
4. Figure out the correct port to announce.
5. Announce that port over the correct interface.

However, this means we'll need to manage multiple mdns "servers".

**Comment by gpestana** [comment]
Will this issue be resolved by #285 or is it blocked by it?

**Comment by Stebalien** [comment]
Blocked by it. It's the "next step". Unfortunately, that PR is blocked because, unless I'm mistaken, it doesn't fix the issue that prompted switching libraries (memory unsafety in the underlying library).

**Comment by gpestana** [comment]
Ok, sounds good. I will keep an eye on this issue and if needed I can look into it when it gets unblocked. In the meanwhile I created an example of how to use go-libp2p mDNS discovery as is nowadays (https://github.com/libp2p/go-libp2p-examples/pull/2). It seems that the high level interface will not change, so I believe that the example will still be relevant when both #285 and this issue are solved.
